export const GET_DOCUMENT_REQUEST = "GET_DOCUMENT_REQUEST";

export const GET_DOCUMENT_SUCCESS = "GET_DOCUMENT_SUCCESS";

export const GET_DOCUMENT_FAILURE = "GET_DOCUMENT_FAILURE";

export const CREATE_DOCUMENT_REQUEST = "CREATE_DOCUMENT_REQUEST";

export const CREATE_DOCUMENT_SUCCESS = "CREATE_DOCUMENT_SUCCESS";

export const CREATE_DOCUMENT_FAILURE = "CREATE_DOCUMENT_FAILURE";

export const UPDATE_DOCUMENT_REQUEST = "UPDATE_DOCUMENT_REQUEST";

export const UPDATE_DOCUMENT_SUCCESS = "UPDATE_DOCUMENT_SUCCESS";

export const UPDATE_DOCUMENT_FAILURE = "UPDATE_DOCUMENT_FAILURE";

export const DELETE_DOCUMENT_REQUEST = "DELETE_DOCUMENT_REQUEST";

export const DELETE_DOCUMENT_SUCCESS = "DELETE_DOCUMENT_SUCCESS";

export const DELETE_DOCUMENT_FAILURE = "DELETE_DOCUMENT_FAILURE";

export const SET_ROLE = "SET_ROLE";
 
export const IMPORT_DOCUMENT_REQUEST =
  "IMPORT_DOCUMENT_REQUEST";

export const IMPORT_DOCUMENT_SUCCESS =
  "IMPORT_DOCUMENT_SUCCESS";

export const IMPORT_DOCUMENT_FAILURE =
  "IMPORT_DOCUMENT_FAILURE";